Repository codestates-seb/seb39_main_045, pull requests merged in 2022-10, with the labels that each got.

#153 feat: member info response impl dummy to real data
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Status.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainSignupDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/response/MemberInfoResponse.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/ChallengeRepository.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, feat

#154 refactor: method call merged when delete member
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, refactoring

#157 feat: delegation module for HistoryService
  server/server/src/main/java/com/cactusvilleage/server/challenge/delegation/DelegationData.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/HistoryRepository.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/S3Upload.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ChallengeTypeValidator.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/InvalidChallengeType.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/HistoryController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/EnrollDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/MorningDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/StudyDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/ThanksDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/StudyResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back, feat

#160 feat: studyService for upload S3 and refactor annotation
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/delegation/DelegationData.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/HistoryController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/EnrollResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/StudyResponseDto.java
Labels: back, feat, refactoring

#162 feat: member status change when chall deleted
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, feat

#163 feat: member info send logic changed
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Status.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainSignupDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/delegation/DelegationData.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Status.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/EnrollResponseDto.java
Labels: back, feat

#166 feat: Validator for field validation and refactor others
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ChallengeTypeValidator.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/TargetDateValidator.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ValidatedChallengeType.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ValidatedTargetDate.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/HistoryController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/EnrollDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/MorningResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back, feat

#165 refactor: select Challenge modal for MainPage
  client/package-lock.json
  client/package.json
  client/src/Routes.tsx
  client/src/feature/challenge/form.ts
  client/src/feature/profile/user.ts
  client/src/store/store.ts
  client/src/types/challengePageTypes.ts
  client/src/types/mainPageTypes.ts
  client/src/types/userTypes.ts
  client/src/utils/challengeApis.ts
  client/src/utils/memberApis.ts
  client/src/views/components/mainpage/AlertModal.tsx
  client/src/views/components/mainpage/SelectModal.tsx
  client/src/views/components/mainpage/ShowTimeInput.tsx
  client/src/views/components/mainpage/SuccessFailModal.tsx
  client/src/views/components/mainpage/TodayChallBtn.tsx
  client/src/views/components/mainpage/TodayChallModal.tsx
  client/src/views/components/mainpage/alertFunction.tsx
  client/src/views/components/mainpage/challVerify.tsx
  client/src/views/components/mainpage/useAlertFlows.tsx
  client/src/views/components/mainpage/useChooseChallFlows.tsx
  client/src/views/pages/MainCactus.tsx
  client/src/views/pages/MainNoCactus.tsx
Labels: front, fix, refactoring

#158 refactor: validate and debounce for Signup form input data
  client/src/feature/form/index.ts
  client/src/utils/debounce.ts
  client/src/utils/validates.ts
  client/src/views/pages/LoginPage/useLoginFlows.tsx
  client/src/views/pages/SignupPage/debouncingChanges.ts
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/useSignupFlows.tsx
  client/src/views/pages/SignupPage/useSignupForm.tsx
Labels: front, refactoring

#170 refactor: studyResponseDto, HistoryStudyService Builder
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/StudyResponseDto.java
Labels: back, refactoring

#174 feat: challenge status, stamp batch processing with scheduler
  server/server/build.gradle
  server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/ChallengeRepository.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJob.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/DiscordWebHookService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/JobLoggerListener.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
Labels: back, feat

#175 feat: challenge batch processing time set to everyday at 12am
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
Labels: back, feat

#171 refactor: validate, debounce, handle error for edit userinfo
  client/src/feature/form/index.ts
  client/src/feature/profile/user.ts
  client/src/types/userTypes.ts
  client/src/views/pages/SettingsPage/debouncingChanges.ts
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.tsx
  client/src/views/pages/SettingsPage/useSettingsForm.tsx
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/useSignupFlows.tsx
Labels: front, refactoring

#184 feat: get active challenge
  server/server/build.gradle
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ChallengeStatus.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/impl/ChallengeStatusValidator.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ActiveChallengeResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/AllChallengesResponseDto.java
Labels: back, feat

#185 refactor: notify request status, error message for Signup, Settings
  client/src/feature/form/index.ts
  client/src/views/components/UI/molecules/text.style.tsx
  client/src/views/pages/SettingsPage/debouncingChanges.ts
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
  client/src/views/pages/SettingsPage/useSettingsPageMounted.ts
  client/src/views/pages/SignupPage/debouncingChanges.ts
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/useSignupFlows.ts
  client/src/views/pages/SignupPage/useSignupFlows.tsx
  client/src/views/pages/SignupPage/useSignupPageMounted.ts
Labels: front, refactoring

#186 fix: challenge progress cal fixed for member info response
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, fix

#193 feat: s3 image download for client to response
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/S3Service.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/HistoryController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ImageController.java
Labels: back, feat

#194 fix: challenge and history mapping issue solved
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
Labels: back, fix

#195 feat: challenge info response dto createdAt field added
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ChallengeInfoResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/impl/ActiveInfoDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/impl/AllInfoDto.java
Labels: back, feat

#198 feat: sheduler time zone set
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJob.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
Labels: back, feat

#199 fix: bean naming fix
  server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
Labels: back, fix

#200 refractor:Modal for mainPage'
  client/src/feature/challenge/form.ts
  client/src/store/store.ts
  client/src/types/mainPageTypes.ts
  client/src/utils/axiosInstance.ts
  client/src/utils/challengeApis.ts
  client/src/views/components/mainpage/AlertModal.tsx
  client/src/views/components/mainpage/SelectModal.tsx
  client/src/views/components/mainpage/SuccessFailModal.tsx
  client/src/views/components/mainpage/TodayChallModal.tsx
  client/src/views/components/mainpage/TodayChallMorning.tsx
  client/src/views/components/mainpage/TodayChallStudy.tsx
  client/src/views/components/mainpage/TodayChallThanks.tsx
  client/src/views/components/mainpage/alertFunction.tsx
  client/src/views/components/mainpage/challVerify.tsx
  client/src/views/components/mainpage/todayChallFunctions.tsx
  client/src/views/components/mainpage/useChooseChallFlows.tsx
  client/src/views/pages/MainCactus.tsx
Labels: front, refactoring

#190 fix: setting up kakao env variables for github actions
  .github/workflows/github-actions-demo.yml
  client/src/views/pages/RankingPage/KakaoShare.tsx
Labels: front, fix

#191 style: UI updates for Ranking page share button, Mypage
  client/src/views/components/UI/molecules/button.style.tsx
  client/src/views/pages/Mypage/index.tsx
  client/src/views/pages/SettingsPage/index.tsx
Labels: front, style

#202 refactor: add type for Mypage states
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/useSignupFlows.ts
Labels: front, refactoring

#203 feat: reselect rtx state, custom get data hook, handle error for Prev…
  client/src/feature/challenge/activeChallenge.ts
  client/src/feature/challenge/previousChallenges.ts
  client/src/feature/form/index.ts
  client/src/feature/totalChallenges/index.ts
  client/src/store/store.ts
  client/src/utils/selectors.ts
  client/src/views/components/UI/Layout.style.ts
  client/src/views/components/icons/mypage/SadCactus.tsx
  client/src/views/components/icons/mypage/index.ts
  client/src/views/pages/PreviousChallenges/Diary.tsx
  client/src/views/pages/PreviousChallenges/DiaryItem.tsx
  client/src/views/pages/PreviousChallenges/Home.tsx
  client/src/views/pages/PreviousChallenges/Morning.tsx
  client/src/views/pages/PreviousChallenges/MorningItem.tsx
  client/src/views/pages/PreviousChallenges/PreviousChallenges.style.ts
  client/src/views/pages/PreviousChallenges/Study.tsx
  client/src/views/pages/PreviousChallenges/StudyItem.tsx
  client/src/views/pages/PreviousChallenges/index.tsx
  client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
Labels: front, feat

#204 feat: member info - chall type default null to none
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, feat

#205 fix: delete module definition for client compile error
  client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
Labels: front, fix

#208 feat: custom get data hook, store state rtx, handle error for Current…
  client/src/feature/challenge/activeChallenge.ts
  client/src/feature/challenge/previousChallenges.ts
  client/src/views/pages/CurrentChallengesPage/CurrentChallengesPage.style.tsx
  client/src/views/pages/CurrentChallengesPage/StatusGraph.tsx
  client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
  client/src/views/pages/CurrentChallengesPage/index.tsx
  client/src/views/pages/CurrentChallengesPage/useCurrentChallenge.ts
  client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
Labels: front, feat

#214 feat: add route for NotFound, Loading page
  client/src/Routes.tsx
  client/src/assets/img/caclogo.jpg
  client/src/views/components/common/Loading.tsx
  client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
  client/src/views/pages/LoadingPage/index.tsx
  client/src/views/pages/NotFoundPage/index.tsx
  client/src/views/pages/index.ts
Labels: front, feat

#213 feat: batch processing logic fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
Labels: back, feat

#216 feat: thanks, morning History service, dto for Challenge Domain Api
  server/server/src/main/java/com/cactusvilleage/server/challenge/delegation/DelegationData.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/MorningController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/StudyController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ThanksController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/MorningDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/HistoryResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/StudyResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back, feat

#218 refactor: extract ranker size to static final
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, refactoring

#219 refactor: package layer and naming refactor
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/JobLoggerListener.java
  server/server/src/main/java/com/cactusvilleage/server/global/infra/email/EmailSender.java
  server/server/src/main/java/com/cactusvilleage/server/global/infra/email/impl/AwsSesSender.java
  server/server/src/main/java/com/cactusvilleage/server/global/infra/webhook/WebHookSender.java
  server/server/src/main/java/com/cactusvilleage/server/global/infra/webhook/impl/DiscordWebHookSender.java
Labels: back, refactoring

#220 fix: static file path changed and apply to method call
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/resources/static/water.txt
Labels: back, fix

#221 refactor: three of Service Controller for RESTful Mapping
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/MorningController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/StudyController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ThanksController.java
Labels: back, refactoring

#222 fix: resource file reading method change
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, fix

#223 refactor: challenge info response dto and variable naming refactor
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ActiveInfoDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/AllInfoDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ChallengeInfoResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/HistoryInfoResponseDto.java
Labels: back, refactoring

#224 refactor: Delegation to Validation for name convention
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ChallengeValidator.java
Labels: back, refactoring

#225 refactor: default message set when reading file failed
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, refactoring

#226 refactor: error response change status code to custom exception code
  server/server/src/main/java/com/cactusvilleage/server/global/response/ErrorResponse.java
Labels: back, refactoring

#227 fix: morning Service module for time diff
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
Labels: back, fix

#228 refactor: overall import and naming refactor
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/OAuth2UserInfo.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/TokenProvider.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/RedisConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainLoginDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/response/MemberInfoResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/ChallengeRepository.java
Labels: back, refactoring

#229 refactor: awsConfig dir to web
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/config/AwsConfig.java
Labels: back, refactoring

#231 fix: duplicate ranker fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, fix

#232 fix: duplicate ranker fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back, fix

#233 fix: ranker index ouf of bounds fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#235 fix: ranker index ouf of bounds fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#236 fix: status, save logic
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
Labels: back 😎, fix 🛠

#215 fix: delete unused module for build error
  client/src/views/pages/NotFoundPage/index.tsx
Labels: front ✨, fix 🛠

#234 refactor:modals for MainPage
  client/src/feature/challenge/form.ts
  client/src/types/mainPageTypes.ts
  client/src/utils/axiosInstance.ts
  client/src/utils/challengeApis.ts
  client/src/views/components/login/style.ts
  client/src/views/components/mainpage/AlertModal.tsx
  client/src/views/components/mainpage/ChooseChallBtn.tsx
  client/src/views/components/mainpage/GiveUpChall.tsx
  client/src/views/components/mainpage/GiveWater.tsx
  client/src/views/components/mainpage/Logout.tsx
  client/src/views/components/mainpage/SelectModal.tsx
  client/src/views/components/mainpage/SuccessFailModal.tsx
  client/src/views/components/mainpage/TodayChallBtn.tsx
  client/src/views/components/mainpage/TodayChallModal.tsx
  client/src/views/components/mainpage/TodayChallMorning.tsx
  client/src/views/components/mainpage/alertFunction.tsx
  client/src/views/components/mainpage/challVerify.tsx
  client/src/views/components/mainpage/todayChallFunctions.tsx
  client/src/views/components/mainpage/useAlertFlows.tsx
  client/src/views/components/mainpage/useChooseChallFlows.tsx
  client/src/views/pages/MainCactus.tsx
  client/src/views/pages/SettingsPage/index.tsx
Labels: front ✨, fix 🛠, refactoring 📌

#238 fix: rankder index ranege fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#237 feat: connect axios instance, store rtx, handle error for Ranking …
  client/src/feature/challenge/activeChallenge.ts
  client/src/feature/ranking/index.ts
  client/src/store/store.ts
  client/src/views/pages/RankingPage/Rankers.tsx
  client/src/views/pages/RankingPage/StampList.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/RankingPage/useRankingPage.ts
  client/src/views/pages/SignupPage/index.tsx
Labels: front ✨, feat 🎇

#240 fix: ranker index bound fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#243 fix: ranker index range fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#244 fix: ranker logic change to solve missing ranker
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#245 fix: ranker index range fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#246 fix: ranker index 500
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, fix 🛠

#247 feat: ranking cal logic fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, feat 🎇

#241 feat: debounce, validate, route path, connect axios request for Forgo…
  client/src/Routes.tsx
  client/src/feature/form/index.ts
  client/src/utils/memberApis.ts
  client/src/views/components/auth/ForgotPassword.tsx
  client/src/views/pages/ForgotPasswordPage/debouncedChanges.ts
  client/src/views/pages/ForgotPasswordPage/index.tsx
  client/src/views/pages/ForgotPasswordPage/useForgotPasswordFlows.ts
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
  client/src/views/pages/index.ts
Labels: front ✨, feat 🎇

#253 refactor:login for client
  client/src/feature/form/index.ts
  client/src/views/components/mainpage/TodayChallStudy.tsx
  client/src/views/pages/LoginPage/index.tsx
  client/src/views/pages/LoginPage/useLoginFlows.tsx
  client/src/views/pages/LoginPage/useLoginForm.tsx
Labels: front ✨, refactoring 📌

#254 feat: initial data set when active challenge is not present
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ActiveInfoDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/AllInfoDto.java
Labels: back 😎, feat 🎇

#256 fix: Service logic because of When registering, it immediately fails
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back 😎, fix 🛠

#255 style: interactive UI, mouse event, link github for CreditPage
  client/src/assets/img/github.png
  client/src/views/components/common/Nav.tsx
  client/src/views/components/icons/credit/AR.tsx
  client/src/views/components/icons/credit/JP.tsx
  client/src/views/components/icons/credit/KH.tsx
  client/src/views/components/icons/credit/MY.tsx
  client/src/views/components/icons/credit/YJ.tsx
  client/src/views/components/icons/credit/intex.ts
  client/src/views/pages/CreditPage/CreditPage.style.ts
  client/src/views/pages/CreditPage/Members.tsx
  client/src/views/pages/SignupPage/index.tsx
Labels: front ✨, style 🎀

#257 feat: redirect non-members to Login for Mypage
  client/src/feature/challenge/form.ts
  client/src/feature/location/index.ts
  client/src/feature/profile/user.ts
  client/src/utils/useRedirectLogoutUser.ts
  client/src/views/pages/CreditPage/index.tsx
  client/src/views/pages/CurrentChallengesPage/useCurrentChallenge.ts
  client/src/views/pages/ForgotPasswordPage/debouncedChanges.ts
  client/src/views/pages/Mypage/index.tsx
  client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
  client/src/views/pages/RankingPage/Rankers.tsx
  client/src/views/pages/RankingPage/StampList.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/RankingPage/rankingConstants.tsx
  client/src/views/pages/RankingPage/useRankingPage.ts
  client/src/views/pages/SettingsPage/debouncingChanges.ts
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
  client/src/views/pages/SettingsPage/useSettingsPageMounted.ts
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/useSignupFlows.ts
Labels: front ✨, feat 🎇

#258 fix: imagePath for fileName Return
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryStudyService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/S3Service.java
Labels: back 😎, fix 🛠

#260 fix: redishash timetolive option fix
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/RefreshToken.java
Labels: back 😎, fix 🛠

#261 fix: all challenge info npe fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/AllInfoDto.java
Labels: back 😎, fix 🛠

#259 refactor: delete unnecessary conditional statement for mypage
  client/src/views/pages/ForgotPasswordPage/useForgotPasswordFlows.ts
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
Labels: front ✨, refactoring 📌

#262 feat: get image src for Challenge Pages
  client/src/feature/challenge/previousChallenges.ts
  client/src/views/components/UI/Layout.style.ts
  client/src/views/pages/CurrentChallengesPage/CurrentChallengesPage.style.tsx
  client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
  client/src/views/pages/CurrentChallengesPage/index.tsx
  client/src/views/pages/PreviousChallenges/PreviousChallenges.style.ts
  client/src/views/pages/PreviousChallenges/StudyItem.tsx
Labels: front ✨, feat 🎇

#263 feat: batch logic feat correctly
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
Labels: back 😎, feat 🎇

#265 fix: redis timetolive delete
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/RefreshToken.java
Labels: back 😎, fix 🛠

#264 feat: change error, default status message for Mypage
  client/src/views/components/UI/Layout.style.ts
  client/src/views/pages/CurrentChallengesPage/index.tsx
  client/src/views/pages/PreviousChallenges/DiaryItem.tsx
  client/src/views/pages/PreviousChallenges/MorningItem.tsx
  client/src/views/pages/PreviousChallenges/StudyItem.tsx
  client/src/views/pages/RankingPage/Rankers.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/RankingPage/useRankingPage.ts
Labels: front ✨, feat 🎇

#266 style: meta open graph, img alt for Web Accessibility, on page SEO
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/ogimage.png
  client/src/index.tsx
  client/src/views/pages/CreditPage/Members.tsx
  client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
  client/src/views/pages/PreviousChallenges/StudyItem.tsx
  client/src/views/pages/RankingPage/KakaoShare.tsx
  client/src/views/pages/RankingPage/TwitterShare.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/RankingPage/useRankingPage.ts
Labels: front ✨, style 🎀

#269 feat: redis security upgrade
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/RedisConfig.java
Labels: back 😎, feat 🎇

#271 feat: email send check logic added when recovery password
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
  server/server/src/main/java/com/cactusvilleage/server/global/infra/email/impl/AwsSesSender.java
Labels: back 😎, feat 🎇

#272 docs: update for README.md
  README.md
Labels: documentation

#274 feat:make Redircts hook to home without Login/make reissue for client
  client/src/App.tsx
  client/src/Routes.tsx
  client/src/feature/form/index.ts
  client/src/index.tsx
  client/src/utils/ProtectRoute.tsx
  client/src/utils/memberApis.ts
  client/src/utils/reissue.ts
  client/src/views/pages/LoginPage/index.tsx
  client/src/views/pages/MainCactus.tsx
  client/src/views/pages/MainNoCactus.tsx
Labels: front ✨

#273 fix: status message, kakao error for Rankings page
  client/src/views/pages/RankingPage/Rankers.tsx
  client/src/views/pages/RankingPage/index.tsx
Labels: front ✨, fix 🛠

#275 refactor: exception code message renaming
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back 😎, refactoring 📌

#276 fix:fix redirect err for client
  client/src/Routes.tsx
  client/src/utils/ProtectRoute.tsx
  client/src/views/components/mainpage/alertFunction.tsx
Labels: front ✨, fix 🛠

#278 fix: morning history service achievement failure conditions
  server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryMorningService.java
Labels: back 😎, fix 🛠

#280 feat: time zone test
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, feat 🎇

#282 refactor:status 401 redirect to login, fix flickering for client
  client/src/App.tsx
  client/src/utils/ProtectRoute.tsx
  client/src/utils/reissue.ts
  client/src/views/components/mainpage/TodayChallStudy.tsx
  client/src/views/components/mainpage/alertFunction.tsx
  client/src/views/components/mainpage/challVerify.tsx
  client/src/views/components/mainpage/main.style.ts
  client/src/views/components/mainpage/todayChallFunctions.tsx
Labels: front ✨, fix 🛠, refactoring 📌

#283 fix:delete console.log
  client/src/views/components/mainpage/todayChallFunctions.tsx
  client/src/views/pages/LoginPage/useLoginFlows.tsx
Labels: front ✨, fix 🛠

#284 refactor: handle response error code 401 for Settings page
  client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
Labels: front ✨, refactoring 📌

#287 feat: time zone test
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
Labels: back 😎, feat 🎇

#289 feat: time zone feat 2
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
Labels: back 😎, feat 🎇

#290 feat: time zone 3
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
Labels: back 😎, feat 🎇

#291 fix: run failed fix
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/HistoryThanksService.java
Labels: back 😎, fix 🛠

#296 fix: change argument for dispatch username
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
Labels: front ✨, fix 🛠

#297 feat: total chall count logic change when send total chall info
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, feat 🎇

#298 feat:explanation modal for mainpage
  client/src/types/mainPageTypes.ts
  client/src/views/components/mainpage/ChooseChallBtn.tsx
  client/src/views/components/mainpage/Explanation.tsx
  client/src/views/components/mainpage/GiveWater.tsx
  client/src/views/components/mainpage/Logout.tsx
  client/src/views/components/mainpage/TodayChallBtn.tsx
  client/src/views/components/mainpage/main.style.ts
  client/src/views/components/mainpage/modal.style.ts
  client/src/views/components/mainpageModal/AlertModal.tsx
  client/src/views/components/mainpageModal/ExplanationModal.tsx
  client/src/views/components/mainpageModal/GiveUpChall.tsx
  client/src/views/components/mainpageModal/ModalPortal.tsx
  client/src/views/components/mainpageModal/SelectModal.tsx
  client/src/views/components/mainpageModal/ShowTimeInput.tsx
  client/src/views/components/mainpageModal/SuccessFailModal.tsx
  client/src/views/components/mainpageModal/TodayChallModal.tsx
  client/src/views/components/mainpageModal/TodayChallMorning.tsx
  client/src/views/components/mainpageModal/TodayChallStudy.tsx
  client/src/views/components/mainpageModal/TodayChallThanks.tsx
  client/src/views/components/mainpageModal/alertFunction.tsx
  client/src/views/components/mainpageModal/challVerify.tsx
  client/src/views/components/mainpageModal/todayChallFunctions.tsx
  client/src/views/components/mainpageModal/useAlertFlows.tsx
  client/src/views/pages/MainCactus.tsx
  client/src/views/pages/MainNoCactus.tsx
  client/src/views/pages/SettingsPage/index.tsx
Labels: front ✨, feat 🎇

#299 feat: chall total date cal logic change
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
Labels: back 😎, feat 🎇

#302 fix: CorsConfig for domain pattern
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
Labels: back 😎, fix 🛠

#300 fix: update Kakao share, redirect uri and change required field for S…
  client/src/feature/form/index.ts
  client/src/views/components/login/KakaoLogin.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.ts
Labels: front ✨, fix 🛠

#303 style:change css modal
  client/src/views/components/mainpage/modal.style.ts
Labels: front ✨, style 🎀

#306 feat: transaction added to custom jpa repo method
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/MemberRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/ChallengeRepository.java
Labels: back 😎, feat 🎇

#307 refactor: naming refactoring
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/api/MemberController.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/ExceptionHandlerFilter.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/AppProperties.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/JobLoggerListener.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
Labels: back 😎, refactoring 📌

#310 hotfix: feature tx and refactor
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/MemberRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/api/MemberController.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/ExceptionHandlerFilter.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/AppProperties.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/ChallengeRepository.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/JobLoggerListener.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
Labels: back 😎, fix 🛠, feat 🎇, refactoring 📌

#309 feat: batch reader change paging to cursor caused by infinite loop
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJobConfig.java
Labels: back 😎, feat 🎇

#313 fix: initial state for OAuth login user edit form
  client/src/views/pages/SettingsPage/useSettingsPageMounted.ts
Labels: front ✨, fix 🛠

#314 fix: setting up default branch for github actions
  .github/workflows/github-actions-demo.yml
Labels: fix 🛠

#315 fix: delete kakaoShare button for RankingPage
  client/src/views/pages/RankingPage/index.tsx
Labels: front ✨, fix 🛠

#316 feat: column option added
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/RefreshToken.java
Labels: back 😎, feat 🎇

#317 fix: fix npe when findall in refresh token repo (redis)
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
Labels: back 😎, fix 🛠
