Repository codestates-seb/seb39_main_045, pull requests merged in 2022-09, with the labels that each got.

#9 feat: Init for server
  server/server/.gitignore
  server/server/build.gradle
  server/server/gradle/wrapper/gradle-wrapper.jar
  server/server/gradle/wrapper/gradle-wrapper.properties
  server/server/gradlew
  server/server/gradlew.bat
  server/server/settings.gradle
  server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
  server/server/src/test/java/com/cactusvilleage/server/ServerApplicationTests.java
Labels: back, feat

#11 fix: init for client
  client/src/App.tsx
  client/src/assets/img/40w40h.png
  client/src/setupTests.ts
Labels: front

#13 update: README for Project Team Name
  README.md
Labels: documentation

#18 feat: improve module for global
  server/server/build.gradle
  server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
  server/server/src/main/java/com/cactusvilleage/server/global/advice/GlobalExceptionAdvice.java
Labels: back, feat

#19 feat: improve module for global / log level
  server/server/src/main/java/com/cactusvilleage/server/global/advice/GlobalExceptionAdvice.java
Labels: back, feat

#30 feat: GlobalVariables, svg for client
  client/public/index.html
  client/src/assets/style/GlobalVariables.ts
  client/src/views/components/common/Nav.tsx
  client/src/views/components/icons/modal/SadCactus.tsx
  client/src/views/components/icons/mypage/Day1.tsx
  client/src/views/components/icons/mypage/Day2.tsx
  client/src/views/components/icons/mypage/Day3.tsx
  client/src/views/components/icons/mypage/Day4.tsx
  client/src/views/components/icons/mypage/Day5.tsx
  client/src/views/components/icons/mypage/Day6.tsx
  client/src/views/components/icons/mypage/Day7.tsx
  client/src/views/components/icons/mypage/GraphL.tsx
  client/src/views/components/icons/mypage/GraphM.tsx
  client/src/views/components/icons/mypage/GraphR.tsx
  client/src/views/components/icons/mypage/SuccessBg.tsx
Labels: front

#31 feat: github actions 설정 for client
  .github/workflows/github-actions-demo.yml
Labels: front, feat

#32 hotfix: github actions 경로 수정 for client
  .github/workflows/github-actions-demo.yml
Labels: front, fix

#35 style: css for Mypage, MypageNowChallenge
  .github/workflows/github-actions-demo.yml
  client/src/App.tsx
  client/src/views/components/common/Nav.tsx
  client/src/views/components/mypage/mypage.ts
  client/src/views/pages/Intro.tsx
  client/src/views/pages/Mypage.tsx
  client/src/views/pages/MypageNowChallenge.tsx
Labels: front, style

#39 feat: Setting up Routes for Mypage
  client/src/App.tsx
  client/src/views/components/mypage/MypageCredit.tsx
  client/src/views/components/mypage/MypageHome.tsx
  client/src/views/components/mypage/MypageNowChallenge.tsx
  client/src/views/components/mypage/MypagePrevChallenges.tsx
  client/src/views/components/mypage/MypageRanking.tsx
  client/src/views/components/mypage/MypageSettings.tsx
  client/src/views/components/mypage/mypage.ts
  client/src/views/pages/Mypage.tsx
  client/src/views/pages/MypageCredit.tsx
  client/src/views/pages/MypageEditUserInfo.tsx
  client/src/views/pages/MypagePrevChallenges.tsx
  client/src/views/pages/MypageRanking.tsx
Labels: front, feat

#54 feat:LoginPage for client
  client/src/views/pages/Login.tsx
Labels: front, style

#58 feat: docker configuration
  server/server/Dockerfile
  server/server/Dockerfile-nginx
  server/server/build.gradle
  server/server/docker-compose.yml
  server/server/nginx.conf
  server/server/src/main/java/com/cactusvilleage/server/global/advice/GlobalExceptionAdvice.java
Labels: back, Infra

#59 Style: UI update for Mypage PrevChallenges
  client/src/views/components/icons/mypage/NoticeCactus.tsx
  client/src/views/components/icons/mypage/SuccessBg.tsx
  client/src/views/components/mypage/MypageHome.tsx
  client/src/views/components/mypage/MypageNowChallenge.tsx
  client/src/views/components/mypage/MypagePrevChallenges.tsx
  client/src/views/components/mypage/MypageSettings.tsx
  client/src/views/components/mypage/PrevChallengeHome.tsx
  client/src/views/components/mypage/PrevDiaryChallenge.tsx
  client/src/views/components/mypage/PrevMorningChallenge.tsx
  client/src/views/components/mypage/PrevStudyChallenge.tsx
  client/src/views/components/mypage/mypage.ts
  client/src/views/components/mypage/mypageStyle.tsx
  client/src/views/pages/Mypage.tsx
Labels: front, style

#62 Style: UI update for Signup
  client/src/views/components/icons/auth/LeftArrow.tsx
  client/src/views/pages/Signup.tsx
Labels: front, style

#68 AWS ECS ALB for NonSecurity
  server/server/src/main/java/com/cactusvilleage/server/global/healthCheck/HealthCheckController.java
  server/server/src/main/java/com/cactusvilleage/server/global/healthCheck/HealthCheckNoSecurity.java
Labels: back, feat

#69 Style: moblie & web UI update for Intro
  client/src/views/components/icons/intro/BigCactusA.tsx
  client/src/views/components/icons/intro/BigCactusB.tsx
  client/src/views/components/intro/BigBottomSlide.tsx
  client/src/views/components/intro/BigTopSlide.tsx
  client/src/views/components/intro/BottomSlide.tsx
  client/src/views/components/intro/Logo.tsx
  client/src/views/components/intro/TopSlide.tsx
  client/src/views/components/intro/introStyle.ts
  client/src/views/pages/Intro.tsx
Labels: front, style

#71 Style: form, resign modal for Mypage Edit UserInfo
  client/src/assets/style/GlobalStyle.ts
  client/src/views/components/mypage/MypageSettings.tsx
  client/src/views/pages/Signup.tsx
Labels: front, style

#75 Feat: task definition
  server/server/task-definition.json
Labels: back, feat, Infra

#74 feat: global - exception code added && single resonse dto impl
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
  server/server/src/main/java/com/cactusvilleage/server/global/response/SingleResponseDto.java
Labels: back, feat

#76 feat: security config, member auth, oauth impl for auth
  server/server/build.gradle
  server/server/src/main/java/com/cactusvilleage/server/auth/email/AwsSesUtils.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Authority.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/RefreshToken.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/OAuth2UserInfo.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/OAuth2UserInfoFactory.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/ProviderType.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/UserPrincipal.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/impl/GoogleOAuth2UserInfo.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/oauth/impl/KakaoOAuth2UserInfo.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/MemberRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/OAuth2AuthorizationRequestRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomUserDetailService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/HeaderUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/SecurityUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/TokenProvider.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/EmailNotDuplicate.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/EmailValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/UsernameNotDuplicate.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/UsernameValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/api/MemberController.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/AwsSesConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/JwtConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/RedisConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/SecurityConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/request/PlainEditDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/request/PlainLoginDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/request/PlainSignupDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/request/RecoveryDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/response/EditResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/response/MemberInfoResponse.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/exception/JwtAccessDeniedHandler.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/exception/JwtAuthenticationEntryPoint.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/JwtExceptionHandlerFilter.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/JwtFilter.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/AppProperties.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/OAuth2AuthenticationFailureHandler.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: back, feat

#79 feat: email form && token logic change
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/RefreshToken.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/HeaderUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/TokenProvider.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/api/MemberController.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/SecurityConfig.java
  server/server/src/main/resources/templates/recovery.html
Labels: back, feat

#81 fix: import added for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, fix

#82 feat: security config change for version control
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/SecurityConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/plain/response/MemberInfoResponse.java
Labels: back, feat

#86 feat: cors config fix
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
Labels: back, feat

#89 refactor: HealthCheckController
  server/server/src/main/java/com/cactusvilleage/server/global/healthCheck/HealthCheckController.java
Labels: back, refactoring

#92 refactor: dto refactoring for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/api/MemberController.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/EditDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainLoginDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainSignupDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/RecoveryDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/response/EditResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/response/MemberInfoResponse.java
Labels: back, refactoring

#84 feat:success fail modal for MainPage
  client/src/views/components/mainpage/Cactus.tsx
  client/src/views/components/mainpage/GiveWater.tsx
  client/src/views/components/mainpage/SuccessFailModal.tsx
  client/src/views/components/mainpage/TodayChallBtn.tsx
  client/src/views/pages/MainCactus.tsx
Labels: front, feat, style

#93 fix: login axios/png for LoginPage
  client/src/assets/img/btn_google_signin_light_normal_web.png
  client/src/assets/img/kakao_login_medium_narrow.png
  client/src/views/pages/Login.tsx
Labels: front, style

#95 fix: cors config fix for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
Labels: back, fix

#96 Feat: kakao & twitter share for Mypage Ranking
  client/public/index.html
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/views/components/icons/mypage/stamps/StampA.tsx
  client/src/views/components/icons/mypage/stamps/StampB.tsx
  client/src/views/components/icons/mypage/stamps/StampC.tsx
  client/src/views/components/icons/mypage/stamps/StampD.tsx
  client/src/views/components/icons/mypage/stamps/StampE.tsx
  client/src/views/components/icons/mypage/stamps/StampF.tsx
  client/src/views/components/icons/mypage/stamps/StampG.tsx
  client/src/views/components/icons/mypage/stamps/StampH.tsx
  client/src/views/components/mypage/KakaoShare.tsx
  client/src/views/components/mypage/MypageRanking.tsx
  client/src/views/components/mypage/StampList.tsx
  client/src/views/components/mypage/TwitterShare.tsx
  client/src/views/pages/Signup.tsx
Labels: front, feat, style

#98 fix: error state, message fix for oauth request
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/OAuth2AuthenticationSuccessHandler.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back, fix

#99 feat: auth exception code change
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomUserDetailService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back, feat

#101 feat: challenge domain
  server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/global/healthcheck/HealthCheckController.java
  server/server/src/main/java/com/cactusvilleage/server/global/healthcheck/HealthCheckNoSecurity.java
Labels: back, feat

#108 feat: permit uri pattern config change
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/SecurityConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/JwtFilter.java
Labels: back, feat

#110 fix: redis config change for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/RedisConfig.java
Labels: back, fix

#111 fix: redis config fix for auth
  server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/RedisConfig.java
Labels: back, fix

#112 fix: duplicate refersh token delete when login
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, fix

#114 Feat/image upload
  server/server/build.gradle
  server/server/src/main/java/com/cactusvilleage/server/challenge/config/AwsConfig.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/S3Upload.java
Labels: back, feat

#113 fix: duplicate refresh token delete when login for social
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/SecurityConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: back, fix

#115 fix: cors config fix for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
Labels: back, fix

#116 feat: username validation
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/SpaceCantBeAtBeginOrEnd.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/SpaceValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/EditDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainSignupDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/RecoveryDto.java
Labels: back, feat

#118 refactor: validator package layer refactoring for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/EmailNotDuplicate.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/SpaceCantBeAtBeginOrEnd.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/UsernameNotDuplicate.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/impl/EmailValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/impl/SpaceValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/impl/UsernameValidator.java
Labels: back, refactoring

#119 'fix: redux initial setting / axiosInstance for client'
  client/src/feature/profile/user.ts
  client/src/index.tsx
  client/src/store/store.ts
  client/src/utils/axiosInstance.tsx
  client/src/views/components/login/style.ts
  client/src/views/pages/Login.tsx
  client/src/views/pages/MainCactus.tsx
Labels: front, fix

#122 fix: change status code and logging level for unsolvable error
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/ExceptionHandlerFilter.java
Labels: back, fix

#123 fix: parsing error fix when check duplicate username for social signup
  server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
Labels: back, fix

#124 fix: rename for PreviousChallenges and delete unused import for Routes
  client/src/views/pages/PreviousChallenges/Diary.tsx
  client/src/views/pages/PreviousChallenges/Home.tsx
  client/src/views/pages/PreviousChallenges/Morning.tsx
  client/src/views/pages/PreviousChallenges/Study.tsx
  client/src/views/pages/PreviousChallenges/index.tsx
  client/src/views/pages/index.ts
Labels: front, fix

#125 fix: parsing error for client
  client/src/utils/axiosInstance.tsx
  client/src/views/components/login/KakaoLogin.tsx
  client/src/views/pages/CurrentChallengesPage/index.tsx
  client/src/views/pages/IntroPage/Logo.style.tsx
  client/src/views/pages/IntroPage/mobile/BottomSlide.tsx
  client/src/views/pages/IntroPage/mobile/TopSlide.tsx
  client/src/views/pages/Login.tsx
  client/src/views/pages/PreviousChallenges/index.tsx
Labels: front, fix

#126 fix: rename style file for client
  client/src/views/components/UI/Layout.style.ts
  client/src/views/components/UI/molecules/button.style.tsx
  client/src/views/components/common/MyPageNav.tsx
  client/src/views/pages/CurrentChallengesPage/index.tsx
  client/src/views/pages/Mypage/index.tsx
  client/src/views/pages/Mypage/mypage.style.tsx
  client/src/views/pages/PreviousChallenges/Diary.tsx
  client/src/views/pages/PreviousChallenges/Home.tsx
  client/src/views/pages/PreviousChallenges/Morning.tsx
  client/src/views/pages/PreviousChallenges/Study.tsx
  client/src/views/pages/PreviousChallenges/index.tsx
  client/src/views/pages/RankingPage/RankingsPage.style.tsx
  client/src/views/pages/RankingPage/StampList.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/SettingsPage/index.tsx
Labels: front, fix

#127 feat: delete refresh token when delete member
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, feat

#128 refactor: abstraction application to mail sender and cookie util to get loose coupling of member service layer
  server/server/src/main/java/com/cactusvilleage/server/auth/email/EmailSender.java
  server/server/src/main/java/com/cactusvilleage/server/auth/email/impl/AwsSesUtils.java
  server/server/src/main/java/com/cactusvilleage/server/auth/repository/OAuth2AuthorizationRequestRepository.java
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/util/impl/JwtCookieUtil.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/JwtConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/SecurityConfig.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/filter/JwtFilter.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/OAuth2AuthenticationFailureHandler.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: back, refactoring

#129 refactor: auth validator naming refactoring
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/EmailNotDuplicate.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/SpaceCantBeAtBeginOrEnd.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/UsernameNotDuplicate.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/impl/EmailDuplicationValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/impl/UsernameDuplicationValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/impl/UsernameSpaceValidator.java
Labels: back, refactoring

#130 feat: create location path Slice in RTX for Nav
  client/package.json
  client/src/feature/challenge/previousChallengesSlice.ts
  client/src/feature/location/locationSlice.ts
  client/src/store/store.ts
  client/src/utils/useSelectorTyped.ts
  client/src/views/components/common/Nav.tsx
  client/src/views/components/common/nav.style.tsx
Labels: front, feat

#134 fix: cookie setting fix for jwt
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
Labels: back, fix

#135 fix: cookie setting fix for jwt - trial 2
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
Labels: back, fix

#136 feat: Challenge domain for enroll challenge
  server/server/.gitignore
  server/server/build.gradle
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/ChallengeTypeValidator.java
  server/server/src/main/java/com/cactusvilleage/server/auth/validator/InvalidChallengeType.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/EditDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainLoginDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainSignupDto.java
  server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/RecoveryDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/entities/History.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/repository/ChallengeRepository.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/HistoryController.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/request/EnrollDto.java
  server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/EnrollResponseDto.java
  server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
Labels: back, feat

#137 fix: cors setting change for cookie
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
Labels: back, fix

#138 fix: cors config fix for localhost
  server/server/src/main/java/com/cactusvilleage/server/auth/web/config/CorsConfig.java
Labels: back, fix

#139 fix: set cookie same site option to none - test
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
Labels: back, fix

#141 refactor: comment delete and duplicate method call delete
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
Labels: back, refactoring

#143 refactor: tracking location without useEffect, code spliting for Client
  client/.eslintrc.js
  client/src/feature/challenge/previousChallengesSlice.ts
  client/src/feature/location/locationSlice.ts
  client/src/lib/constants.ts
  client/src/views/components/UI/Animation.style.tsx
  client/src/views/components/UI/Layout.style.ts
  client/src/views/components/UI/molecules/text.style.tsx
  client/src/views/components/common/MyPageNav.tsx
  client/src/views/components/common/Nav.tsx
  client/src/views/pages/CurrentChallengesPage/StatusGraph.tsx
  client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
  client/src/views/pages/CurrentChallengesPage/index.tsx
  client/src/views/pages/IntroPage/Intro.style.ts
  client/src/views/pages/IntroPage/Intro.style.tsx
  client/src/views/pages/IntroPage/Logo.style.tsx
  client/src/views/pages/IntroPage/pc/BigBottomSlide.tsx
  client/src/views/pages/IntroPage/pc/BigTopSlide.tsx
  client/src/views/pages/Mypage/index.tsx
  client/src/views/pages/Mypage/mypage.style.tsx
  client/src/views/pages/PreviousChallenges/Morning.tsx
  client/src/views/pages/PreviousChallenges/PreviousChallenges.style.ts
  client/src/views/pages/PreviousChallenges/Study.tsx
  client/src/views/pages/PreviousChallenges/index.tsx
  client/src/views/pages/RankingPage/Rankers.tsx
  client/src/views/pages/RankingPage/RankingsPage.style.tsx
  client/src/views/pages/RankingPage/StampList.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/SettingsPage/SettingsPage.style.ts
  client/src/views/pages/SettingsPage/index.tsx
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/signup.style.ts
Labels: front, refactoring

#145 cookie setting change for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
Labels: back, fix

#148 fix: cookie config fix for auth
  server/server/src/main/java/com/cactusvilleage/server/auth/util/CookieUtil.java
Labels: back, fix

#147 feat: initial settings for custom api hooks
  client/src/feature/location/index.ts
  client/src/feature/totalChallenges/index.ts
  client/src/views/components/common/Nav.tsx
  client/src/views/pages/SettingsPage/useSettingsFlows.tsx
  client/src/views/pages/SettingsPage/useSettingsForm.tsx
  client/src/views/pages/SignupPage/index.tsx
  client/src/views/pages/SignupPage/useSignupFlows.tsx
  client/src/views/pages/SignupPage/useSignupForm.tsx
Labels: front, feat

#151 style: graphic attribution, interactive UI for Credit Page
  client/src/store/store.ts
  client/src/views/components/UI/Layout.style.ts
  client/src/views/components/UI/atoms/static.style.tsx
  client/src/views/components/common/MyPageNav.tsx
  client/src/views/pages/CreditPage/Attributions.tsx
  client/src/views/pages/CreditPage/CreditPage.style.ts
  client/src/views/pages/CreditPage/Members.tsx
  client/src/views/pages/CreditPage/index.tsx
  client/src/views/pages/Mypage/mypage.style.tsx
  client/src/views/pages/PreviousChallenges/Home.tsx
  client/src/views/pages/PreviousChallenges/PreviousChallenges.style.ts
  client/src/views/pages/PreviousChallenges/Study.tsx
  client/src/views/pages/PreviousChallenges/index.tsx
  client/src/views/pages/RankingPage/RankingsPage.style.tsx
  client/src/views/pages/RankingPage/StampList.tsx
  client/src/views/pages/RankingPage/index.tsx
  client/src/views/pages/SignupPage/SignupPage.style.ts
Labels: front, style

#152 refactor: member info response refactor - provider type upper -> lower
  server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
Labels: back, refactoring
